import fs from "fs";
import path from "path";
import crypto from "crypto";
import { execFile } from "child_process";
import { promisify } from "util";
import { DockerManager } from "./docker-manager";
import { GitManager } from "./git-manager";

const exec = promisify(execFile);

const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";
const SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

type ProgressFn = (step: string, percent: number) => void;

export class SetupManager {
  private dataDir: string;
  private docker: DockerManager;
  private git: GitManager;
  private adminEmail: string | null = null;
  private adminPassword: string | null = null;
  private adminResolve: (() => void) | null = null;

  constructor(dataDir: string, docker: DockerManager, git: GitManager) {
    this.dataDir = dataDir;
    this.docker = docker;
    this.git = git;
  }

  setAdminCredentials(email: string, password: string) {
    this.adminEmail = email;
    this.adminPassword = password;
    // Resume setup if it was waiting
    if (this.adminResolve) {
      this.adminResolve();
      this.adminResolve = null;
    }
  }

  private async waitForAdminCredentials(onProgress: ProgressFn): Promise<void> {
    if (this.adminEmail && this.adminPassword) return;

    // Signal the UI to show the admin form
    onProgress("__SHOW_ADMIN_FORM__", 88);

    // Wait until setAdminCredentials is called
    await new Promise<void>((resolve) => {
      this.adminResolve = resolve;
    });
  }

  async isFirstRun(): Promise<boolean> {
    const envFile = path.join(this.dataDir, "code", ".env.local");
    return !fs.existsSync(envFile);
  }

  async runSetup(onProgress: ProgressFn): Promise<void> {
    // Step 1: Create data directory
    onProgress("Creating data directory...", 5);
    fs.mkdirSync(this.dataDir, { recursive: true });

    // Step 2: Check Docker
    onProgress("Checking Docker...", 10);
    if (!(await this.docker.isDockerInstalled())) {
      const url = this.docker.getDockerInstallUrl();
      throw new Error(
        `Docker is not installed. Please install Docker Desktop from:\n${url}\n\nAfter installing, restart MediaHub.`
      );
    }

    if (!(await this.docker.isDockerRunning())) {
      throw new Error(
        "Docker is installed but not running.\n\nPlease start Docker Desktop and restart MediaHub."
      );
    }

    // Step 3: Clone code from GitHub
    onProgress("Downloading MediaHub code...", 15);
    const codeDir = path.join(this.dataDir, "code");
    if (!(await this.git.isCloned())) {
      await this.git.clone((phase, loaded, total) => {
        const pct = total > 0 ? Math.round((loaded / total) * 100) : 0;
        onProgress(`Downloading: ${phase} (${pct}%)`, 15 + Math.round(pct * 0.2));
      });
    }

    // Step 4: Generate environment file
    onProgress("Configuring environment...", 40);
    await this.generateEnvFile(codeDir);

    // Step 5: Generate SSL certificates
    onProgress("Setting up HTTPS certificates...", 45);
    await this.generateSSLCerts(codeDir);

    // Step 6: Start Docker services
    onProgress("Starting services (first time takes ~3 minutes)...", 50);
    await this.docker.startServices();

    // Step 7: Wait for database
    onProgress("Waiting for database...", 70);
    await this.docker.waitForDatabase();

    // Wait a bit more for GoTrue (auth) to initialize
    await new Promise((r) => setTimeout(r, 5000));

    // Step 8: Run migrations
    onProgress("Setting up database tables...", 80);
    await this.docker.runMigrations();

    // Step 9: Ask user for admin credentials
    await this.waitForAdminCredentials(onProgress);

    // Step 10: Create admin account
    onProgress("Creating admin account...", 90);
    await this.createAdminAccount();

    // Step 11: Wait for app
    onProgress("Waiting for app to start...", 95);
    await this.docker.waitForApp();

    onProgress("MediaHub is ready!", 100);
  }

  private async generateEnvFile(codeDir: string): Promise<void> {
    const envPath = path.join(codeDir, ".env.local");
    if (fs.existsSync(envPath)) return;

    const encryptionKey = crypto.randomBytes(32).toString("hex");
    const cronSecret = crypto.randomBytes(16).toString("hex");

    const envContent = `# Auto-generated by MediaHub Desktop
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_KEY}
REDIS_URL=redis://localhost:6379
TOKEN_ENCRYPTION_KEY=${encryptionKey}
NEXT_PUBLIC_APP_URL=https://localhost:3443
CRON_SECRET=${cronSecret}
`;

    fs.writeFileSync(envPath, envContent);
  }

  private async generateSSLCerts(codeDir: string): Promise<void> {
    const certPath = path.join(codeDir, "localhost+1.pem");
    const keyPath = path.join(codeDir, "localhost+1-key.pem");

    if (fs.existsSync(certPath) && fs.existsSync(keyPath)) return;

    // Generate self-signed certificate using openssl
    try {
      await exec("openssl", [
        "req", "-x509", "-newkey", "rsa:2048",
        "-keyout", keyPath,
        "-out", certPath,
        "-days", "365",
        "-nodes",
        "-subj", "/CN=localhost",
        "-addext", "subjectAltName=DNS:localhost,IP:127.0.0.1",
      ]);
    } catch {
      // openssl might not be available on Windows — create a dummy cert warning
      console.warn("Could not generate SSL certificates with openssl.");
      console.warn("On Windows, install OpenSSL or use mkcert.");

      // Try mkcert as fallback
      try {
        await exec("mkcert", ["-install"]);
        await exec("mkcert", ["-cert-file", certPath, "-key-file", keyPath, "localhost", "127.0.0.1"], {
          cwd: codeDir,
        });
      } catch {
        throw new Error(
          "Could not generate SSL certificates.\n\n" +
          "Please install OpenSSL or mkcert:\n" +
          "  Mac: brew install mkcert\n" +
          "  Windows: choco install mkcert\n" +
          "  Linux: sudo apt install mkcert"
        );
      }
    }
  }

  private async createAdminAccount(): Promise<void> {
    const email = this.adminEmail!;
    const password = this.adminPassword!;

    try {
      const http = await import("http");
      const postData = JSON.stringify({
        email,
        password,
        email_confirm: true,
        user_metadata: { name: "Super Admin" },
      });

      await new Promise<void>((resolve, reject) => {
        const req = http.request(
          {
            hostname: "127.0.0.1",
            port: 54321,
            path: "/auth/v1/admin/users",
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              apikey: SUPABASE_SERVICE_KEY,
              Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
              "Content-Length": Buffer.byteLength(postData),
            },
          },
          (res) => {
            let body = "";
            res.on("data", (chunk) => (body += chunk));
            res.on("end", () => {
              if (res.statusCode === 200 || res.statusCode === 201) {
                resolve();
              } else if (body.includes("already been registered")) {
                resolve(); // Already exists
              } else {
                reject(new Error(`Failed to create admin: ${body}`));
              }
            });
          }
        );
        req.on("error", reject);
        req.write(postData);
        req.end();
      });
    } catch (error: any) {
      console.warn("Admin account creation failed:", error.message);
      // Non-fatal — user might already exist
    }
  }
}
