#!/bin/bash
# ============================================
# MediaHub — First-Time Docker Setup
# ============================================
# Run this ONCE when setting up a new dev machine.
# Usage: bash scripts/docker-setup.sh
#
# What it does:
#   1. Generates SSL certificates (if missing)
#   2. Creates .env.local with all required variables
#   3. Builds and starts all Docker services
#   4. Waits for services to be ready
#   5. Runs database migrations
#   6. Creates the default super admin user
#
# After this, just use: docker compose up

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo ""
echo "=========================================="
echo "  MediaHub — First-Time Setup"
echo "=========================================="
echo ""

# ─── Step 0: Check Docker is installed ───
echo "0. Checking Docker..."
if ! command -v docker &> /dev/null; then
  echo ""
  echo "   Docker is not installed. Please install it first:"
  echo ""
  echo "   Mac:     https://docs.docker.com/desktop/install/mac-install/"
  echo "   Ubuntu:  https://docs.docker.com/engine/install/ubuntu/"
  echo "   Windows: https://docs.docker.com/desktop/install/windows-install/"
  echo "   Other:   https://docs.docker.com/get-docker/"
  echo ""
  echo "   After installing, make sure Docker is running, then re-run:"
  echo "   bash scripts/docker-setup.sh"
  exit 1
fi

# Check Docker is actually running
if ! docker info &> /dev/null; then
  echo ""
  echo "   Docker is installed but not running. Please start it:"
  echo ""
  echo "   Mac/Windows: Open Docker Desktop and wait for it to start"
  echo "   Linux:       sudo systemctl start docker"
  echo ""
  echo "   Then re-run: bash scripts/docker-setup.sh"
  exit 1
fi

# Check docker compose is available
if ! docker compose version &> /dev/null; then
  echo ""
  echo "   'docker compose' command not found."
  echo "   Please update Docker to the latest version."
  echo "   https://docs.docker.com/get-docker/"
  exit 1
fi

echo "   Docker $(docker --version | sed 's/Docker version //' | cut -d, -f1) — OK"
echo ""

# ─── Step 1: Generate SSL certificates ───
echo "1. Checking SSL certificates..."
if [ -f "localhost+1.pem" ] && [ -f "localhost+1-key.pem" ]; then
  echo "   Certificates already exist — skipping"
else
  echo "   Generating SSL certificates with mkcert..."

  # Install mkcert if not available
  if ! command -v mkcert &> /dev/null; then
    if [ "$(uname)" = "Darwin" ]; then
      echo "   Installing mkcert via Homebrew..."
      brew install mkcert
      mkcert -install
    elif [ "$(uname)" = "Linux" ]; then
      echo "   Downloading mkcert for Linux..."
      curl -Lo mkcert "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
      chmod +x mkcert
      sudo mv mkcert /usr/local/bin/
      mkcert -install
    fi
  fi

  mkcert localhost 127.0.0.1
  echo "   Certificates generated: localhost+1.pem, localhost+1-key.pem"
fi
echo ""

# ─── Step 2: Create .env.local ───
echo "2. Checking .env.local..."
if [ -f ".env.local" ]; then
  echo "   .env.local already exists — skipping"
  echo "   (Delete it and re-run if you want a fresh config)"
else
  echo "   Generating TOKEN_ENCRYPTION_KEY..."
  ENCRYPTION_KEY=$(openssl rand -hex 32)

  cat > .env.local << EOF
# ============================================
# MediaHub — Local Development (Docker)
# ============================================
# Auto-generated by scripts/docker-setup.sh

# ─── Supabase (Docker) ───
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

# ─── Redis (Docker) ───
REDIS_URL=redis://localhost:6379

# ─── Encryption ───
TOKEN_ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ─── App URL ───
NEXT_PUBLIC_APP_URL=https://localhost:3443

# ─── Cron Secret ───
CRON_SECRET=dev-cron-secret
EOF

  echo "   Created .env.local with generated encryption key"
fi
echo ""

# ─── Step 3: Build and start services ───
echo "3. Building and starting Docker services..."
echo "   This may take a few minutes on first run..."
docker compose up -d --build
echo "   All services starting..."
echo ""

# ─── Step 4: Wait for services ───
echo "4. Waiting for services to be ready..."

echo -n "   Database: "
for i in $(seq 1 30); do
  if docker compose exec -T db pg_isready -U supabase_admin -d supabase > /dev/null 2>&1; then
    echo "ready"
    break
  fi
  if [ $i -eq 30 ]; then
    echo "TIMEOUT — database did not start in time"
    exit 1
  fi
  sleep 2
done

echo -n "   Auth (GoTrue): "
for i in $(seq 1 30); do
  if docker compose exec -T db env PGPASSWORD=postgres psql -U supabase_admin -d supabase -c "SELECT 1 FROM auth.users LIMIT 0" > /dev/null 2>&1; then
    echo "ready"
    break
  fi
  if [ $i -eq 30 ]; then
    echo "TIMEOUT — auth service did not start in time"
    exit 1
  fi
  sleep 2
done

echo -n "   Redis: "
for i in $(seq 1 15); do
  if docker compose exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
    echo "ready"
    break
  fi
  if [ $i -eq 15 ]; then
    echo "TIMEOUT"
    exit 1
  fi
  sleep 2
done

echo -n "   API Gateway (Kong): "
for i in $(seq 1 15); do
  if curl -s http://localhost:54321/rest/v1/ > /dev/null 2>&1; then
    echo "ready"
    break
  fi
  if [ $i -eq 15 ]; then
    echo "TIMEOUT"
    exit 1
  fi
  sleep 2
done
echo ""

# ─── Step 5: Run database migrations ───
echo "5. Setting up database..."
CONTAINER="media_publisher-db-1"
DB_USER="supabase_admin"
DB_PASS="postgres"
DB_NAME="supabase"

echo "   Applying main schema..."
docker exec -i "$CONTAINER" env PGPASSWORD="$DB_PASS" psql -U "$DB_USER" -d "$DB_NAME" < src/server/db/schema.sql > /dev/null 2>&1
echo "   OK"

echo "   Applying migrations..."
for migration in supabase/migrations/*.sql; do
  if [ -f "$migration" ]; then
    echo "   - $(basename $migration)"
    docker exec -i "$CONTAINER" env PGPASSWORD="$DB_PASS" psql -U "$DB_USER" -d "$DB_NAME" < "$migration" 2>&1 | grep -i "error" || true
  fi
done
echo "   OK"

echo "   Reloading PostgREST schema cache..."
docker restart media_publisher-rest-1 > /dev/null 2>&1 || true
sleep 2
echo "   OK"
echo ""

# ─── Step 6: Create super admin ───
echo "6. Creating default super admin..."
bash scripts/create-superadmin.sh
echo ""

# ─── Done ───
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "  All services are running. Open:"
echo ""
echo "    App:       https://localhost:3443"
echo "    Studio:    http://localhost:54323"
echo "    Inbucket:  http://localhost:54324"
echo ""
echo "  Login with:"
echo "    Email:     pranjul@deepvidya.ai"
echo "    Password:  123456"
echo ""
echo "  Daily start: docker compose up"
echo "  Stop:        docker compose down"
echo "  Logs:        docker compose logs -f app worker"
echo ""
